### NumPy & In-built functions

Numpy means Numerical python.
NumPy is a general-purpose array-processing package.It provides a high-perfromance multi-dimensional array object,and tools for working with these arrays. It is fundamental package for scientific computing with python.

#### What is an Array ? 

An array is a data structure that stores values of same data type. In python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [1]:
# Initially lets import NumPy
import numpy as np

In [2]:
my_list=[1,2,3,4,5]
arr =np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [6]:
arr                              # It's one-dimensional array

array([1, 2, 3, 4, 5])

In [5]:
arr.shape        #since it is 1-dimesnional array & has 5 elements present inside array. so we are getting 5,

(5,)

In [ ]:
#we can convert this into 2-dimesnional array by using reshape.


In [16]:
#Multi-nested array
list1 = [1,2,3,4,5]                 #here we are converting our 3 lists into an array by using function
list2 = [2,3,4,5,6]
list3 = [9,7,6,8,9]

arr = np.array([list1,list2,list3])

In [17]:
arr       #Its a 2-dimesional array. In this we can absorb there are 2 square braces open at beginning and 2 are closed at end.
             
                         

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
# check the shape of the array
arr.shape    # there are 3 rows and 5 coloumns present in 2 dimensional array.

(3, 5)

#### The reason we are using arrays because their operations are very fast and arrays are extensively used in Exploratory data analysis(EDA) and in Feature engineering.

In [10]:
#we can reshape the size of above 2-dimensional array by using inbuilt functional called reshape.
arr.reshape(5,3)    

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

We are creating new array by just reshaping the old array but always remember the no. of elements should be the equal.

In [11]:
arr.reshape(1,15) #we can also convert this into one row and 15 col and it gives a list but it always be 2-dimensional

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [12]:
arr.reshape(5,4)   #we can only reshape to same elements 

ValueError: cannot reshape array of size 15 into shape (5,4)

#### Indexing

In [14]:
# Accessing the array elements or retrieving the data inside an array.
arr=np.array([1,2,3,4,5,6,7,8,9])   #In array the indexes starts from 0.

In [15]:
arr[3]

4

In [18]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
arr[:,:]                    #left side colon is row and right side is always column

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr[0:2,:]            #for accessing 0 and 1st row of index in above array.

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [22]:
#if we want to access first 2 rows and first 2 columns in array 
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [26]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [27]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [28]:
arr[1:2,1:4]           #for accessing 3,4,5 in array

array([[3, 4, 5]])

In [30]:
#In-built function
arr = np.arange(0,10)          #if u press shift+tab on arange u can see on docstring arange has 3 parameters start,stop,step

In [31]:
arr       # Between 0 to 10 all the elements will be shown.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr = np.arange(0,10,step=2)

In [33]:
arr       #it is now taking step gap of 2 here until 10

array([0, 2, 4, 6, 8])

In [34]:
#another funcrion
np.linspace(1,10,50) #If I want 50 Points or values in b/w 1 to 10.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [45]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#copy function(*imp)  if we want to replace 100 from3 index to last index in array
arr[3:,]=100

In [47]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [48]:
arr1=arr

In [49]:
arr1[3:]=500

In [50]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

Array is an refrence type. 

In [52]:
print(arr1)
arr1[3:]=1000
arr1

[  1   2   3 500 500 500 500 500 500]


array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

#### Some conditions very useful in EDA.

In [64]:
val = 2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [65]:
#For getting the exact elements which are less than 2
arr[arr<2]

array([1])

In [66]:
#elements less than 300
arr[arr<300]

array([1, 2, 3])

In [56]:
arr%2   #we can do modulus

array([1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [57]:
arr/2  #we can do division

array([  0.5,   1. ,   1.5, 500. , 500. , 500. , 500. , 500. , 500. ])

In [68]:
# Create Arrays and Reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
arr1=np.arange(0,10).reshape(2,5)

In [85]:
arr2=np.arange(0,10).reshape(2,5)

In [88]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [89]:
np.ones(4)  #creates an array where all elements are replaced by 1
               #if u check shift+tab docstring then u can see by-default dtype=float. So here below we are getting 1.,1.,

array([1., 1., 1., 1.])

In [91]:
#if we change dtype to integer
np.ones(4,dtype=int)

array([1, 1, 1, 1])

For 2-dimensional array

In [92]:
np.ones((2,5),dtype=int)   #2 is row and 5 is column

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [93]:
#random distribution
np.random.rand(3,3)   #if u put shape 3,3 then it's giving random elements which are selected by-default from 0 to 1.

array([[0.71763819, 0.10192172, 0.3282052 ],
       [0.51630002, 0.67005148, 0.43554163],
       [0.38997741, 0.51476068, 0.1561361 ]])

In [94]:
np.random.randn(4,4)    #it will select the random variable based on standard normal distribution

array([[-0.2473502 ,  0.33874175, -0.00372822, -0.41701074],
       [-0.16180297, -1.91780867,  1.21310146, -0.04327706],
       [-0.44496513,  0.0144266 ,  0.30614354,  1.02343012],
       [-0.14677605,  0.56779792, -0.55406765, -1.07193015]])

In [97]:
np.random.randint(0,100,8)

array([79, 30, 72, 54, 89, 80, 94, 96])

In [98]:
#reshape
np.random.randint(0,100,8).reshape(2,4)

array([[29,  1, 47, 64],
       [66, 19, 13, 31]])

In [100]:
np.random.random_sample((2,5))

array([[0.83790611, 0.32168396, 0.20017505, 0.50519889, 0.76703805],
       [0.37683969, 0.40264188, 0.0224804 , 0.44509472, 0.95537835]])

## Pandas

Pandas is an open source,BSD-licensed library providing high performance,easy to use data structures and data analysis tools for the python programming language.

* what is Data Frames?
* what is Data series?
* Different operations in pandas

In [110]:
#First step is to import pandas
import pandas as pd
import numpy as np

In excelsheet or csv files there are data in different rows ,features(columns) and if i want to read the data we use pandas.

In [144]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Column4"])

In [125]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [127]:
# Accessing the elements 2 ways 1 .loc , 2 .iloc
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [148]:
df['Column1']  #without using loc and iloc functions we can access rows and columns directly.

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [149]:
df[['Column3','Column4']] #Acessing 2 columns

Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [130]:
#we can convert the dataframe into csv(comma separated values)
df.to_csv('Test1.csv')

DataFrame- is a 2-dimesnsional data structure,or a table of rows and columns
series- is a one-dimensional array holding data of any type.Any one row or column can be series

In [131]:
#check the type
type(df.loc['Row1'])

pandas.core.series.Series

In [132]:
df.iloc[:,:]     #simarly like arrays in numpy left side is row and right is column

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [133]:
#above we are getting all rows and columns

In [135]:
#Accessing the 2 rows and 2 columns by indexing
df.iloc[0:2,0:2]

Column1  Column2
Row1        0        1
Row2        4        5

In [136]:
#type
type(df.iloc[0:2,0:2])   #data frame coz we have more than one row or column

pandas.core.frame.DataFrame

In [137]:
#convert Data Frames into Arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [138]:
#we can see the shape as well
df.iloc[:,1:].values.shape

(5, 3)

#### For checking missing values in a data set 

In [140]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [145]:
#if we want to find out how many unique categories we have in dataset
df['Column1'].value_counts()

0     1
8     1
4     1
16    1
12    1
Name: Column1, dtype: int64

In [147]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])